site_name: The LOGIQ Glossary for Observability and Kubernetes
site_url: https://glossary.logiq.ai/

theme:
  name: null
  custom_dir: material
  favicon: media/favicon.png
  logo: media/logiq-white.png
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  palette:
    - scheme: slate
      primary: pink
      accent: pink 
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top 
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/logiqai
      name: Fork LOGIQ on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/logiq_ai
      name: Follow LOGIQ on Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCknndR4L6qUZdHq0L7H3Zlg
      name: Watch LOGIQ videos on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/logiq-ai/
      name: Join LOGIQ on LinkedIn
  analytics:
    provider: google
    property: G-FM1WSDN735
  homepage: https://logiq.ai/

nav:
- Home: index.md
- Observability:
  - Home: observability/index.md
  - AIOps: observability/aiops.md
  - Cardinality: observability/cardinality.md
  - Context: observability/context.md
  - Dimensionality: observability/dimensionality.md
  - Events: observability/events.md
  - Logs: observability/logs.md
  - Metadata: observability/metadata.md
  - Metrics: observability/metrics.md
  - Sources: observability/sources.md
  - Traces: observability/traces.md
- Kubernetes:
  - Home: kubernetes/index.md
  - Cluster: kubernetes/cluster.md
  - Container: kubernetes/container.md
  - Control plane: kubernetes/control-plane.md
  - K3s: kubernetes/k3s.md
  - kubeadm: kubernetes/kubeadm.md
  - Kubernetes API: kubernetes/the-kubernetes-api.md
  - kubectl: kubernetes/kubectl.md
  - MicroK8s: kubernetes/microk8s.md
  - Microservices: kubernetes/microservices.md
  - Namespace: kubernetes/namespace.md
  - Nodes: kubernetes/nodes.md
  - Pods: kubernetes/pods.md



